server.port=${PORT:8080}
spring.application.name=collablearn-backend

spring.data.mongodb.uri=mongodb+srv://a34109745_db_user:y3fvSRx0Cfbdcezo@cluster0.xhiywra.mongodb.net/collablearn?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=mongodb+srv://a34109745_db_user:y3fvSRx0Cfbdcezo@cluster0.xhiywra.mongodb.net/collablearn?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=collablearn

brevo.api.key=${BREVO_API_KEY:}
mail.from=${MAIL_FROM:emmanueljebba8@gmail.com}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}