server.port=${PORT:8080}
spring.application.name=collablearn-backend

spring.data.mongodb.uri=mongodb+srv://a34109745_db_user:y3fvSRx0Cfbdcezo@cluster0.xhiywra.mongodb.net/collablearn?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=mongodb+srv://a34109745_db_user:y3fvSRx0Cfbdcezo@cluster0.xhiywra.mongodb.net/collablearn?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=collablearn

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}